### ISSUE TITLE
Expose async logging for backends

### ISSUE THREAD

**Issue by padenot** [mozilla/cubeb-rs#66]
Logging from the real-time thread really needs to be done using [async logging](https://searchfox.org/mozilla-central/source/media/libcubeb/src/cubeb_log.h#55-60).

At the moment, doing any logging that is ever so slightly non-trivial (and I'm talking formatting four floats in a string here) will glitch, on my Macbook Pro 2018 running with 128-frames buffer duplex stream.

**Comment by ashleyz** [comment]
#70 has been merged + adds async logging support. Closing issue, please feel free to reopen if additional work is required.
